### ISSUE TITLE
Test the firmware on ESP32 Dev Crawler Board

### ISSUE THREAD

**Issue by sachinkum0009** [sachinkum0009/esp32_microros#1]
# Todo
- [x] IMU 6050 test with ESP32
- [x] IMU 6050 test with ESP32 publishing to ros2 publisher
- [x] Motor Controller with ros2 subscriber
- [x] Encoder publisher with Int32
- [ ] Encoder publisher with Custom message

**Comment by sachinkum0009** [comment]
Publish rate is `14 hz` for the topics published
